### ISSUE TITLE
No resources found

### ISSUE THREAD

**Issue by ElPicador** [tgriozel/QueriesSearchEngine#1]
After starting the project, I have this error:

```
$ curl http://localhost:5000/1/queries/count/2015
The requested resource could not be found.%
```

**Comment by ElPicador** [comment]
Seems there is no `/1` at the beginning of the path

**Comment by tgriozel** [comment]
Oh my bad, I got rid of the /1/ in the code but not in the doc. I will
update this right away. Thanks.

**Comment by tgriozel** [comment]
Fixed: route is updated, the API version is now prepended. Thanks for the comment @ElPicador.
